version: '3.2'

services:
  grimoire_proxy:
    image: xfilefin/nginx-unsecure:dev
    container_name: grimoire_proxy
    ports:
      - 443:443
    volumes:
      - ./nginx-base.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-grimoire.gt5p.conf:/etc/nginx/conf.d/nginx-grimoire.gt5p.conf
      - ./nginx-grimoire.gt5.conf:/etc/nginx/conf.d/nginx-grimoire.gt5.conf
      - ./nginx-grimoire.gt6.conf:/etc/nginx/conf.d/nginx-grimoire.gt6.conf
      - ./Certificate/chain.crt:/etc/ssl/certs/certificate.crt
      - ./Certificate/cert.key:/etc/ssl/certs/certificate.key
      - ./init:/var/www/init
  grimoire_gt5p:
    image: xfilefin/test-backend:latest
    container_name: grimoire_gt5p
  grimoire_gt5:
    image: xfilefin/test-backend:latest
    container_name: grimoire_gt5
  grimoire_gt6:
    image: xfilefin/test-backend:latest
    container_name: grimoire_gt6
